[tool.poetry]
name = "familybudget"
version = "0.1.0"
description = ""
authors = ["Martin Wanczyk <wanczyk.martin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "4.1.2"
djangorestframework = "^3.14.0"
psycopg2 = "^2.9.5"
dj-rest-auth = {extras = ["with-social"], version = "^2.2.6"}
djangorestframework-simplejwt = "^5.2.2"
drf-nested-routers = "^0.93.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
